version: '3.8'

services:
  torch-horovod:
    container_name: torch-horovod
    hostname: torch-horovod
    image: horovod/horovod:latest
    tty: true
    stdin_open: true
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            # device_ids: ['0']
            capabilities: [gpu]
    privileged: true
    shm_size: 64g
    volumes:
      - /root/.ssh:/root/.ssh
      - /root/projects/hello-horovod:/root/workspace
    environment:
      - TZ=Asia/Seoul
      - DISPLAY=<YOUR-X-SERVER-ADDRESS>:0
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
